// 実パス: macos/Packages/DesignSystem/Tests/DesignSystemTests/Acceptance/AcceptancePermissionWordingTests.swift
// task-50（UX-10b）受け入れテスト（PM 著・不変）。UIWording+Permissions 未実装のコンパイル RED が正常。
// 期待値は tasks/task-50.md の独立リテラル。製品の辞書・列挙・出力から生成しない。
// 公開面の解釈は task-48 凍結テストに従う: enum UIWording / enum Key: String, CaseIterable / text(_:languageCode:)
//
// 凍結する公開面（UIWording.swift は変更せず、本ファイルが要求する拡張を UIWording+Permissions.swift に置く）:
//   enum UIWording.PermissionAgent: String, CaseIterable, Equatable, Hashable, Sendable
//   enum UIWording.PermissionKind: String, CaseIterable, Equatable, Hashable, Sendable
//   struct UIWording.PermissionWording: Equatable, Hashable, Sendable { title, explanation }
//   struct UIWording.LaunchPermissionWording: Equatable, Hashable, Sendable { rowLabel, offExplanation, onExplanation }
//   static func permission(agent:kind:value:languageCode:) -> PermissionWording
//   static func launchPermission(agent:displayName:languageCode:) -> LaunchPermissionWording
//   static func settingsPermissionFooter(languageCode:) -> String
// 言語: task-48 と同じ。主言語（`-` / `_` の前）を大小無視。en は英語、ja は日本語、それ以外は日本語。
// default と manual は同じ表示。正本は nil → bypass へ倒さない。Cursor 動作モード nil は Agent。Codex プロフィール nil は未選択。

import Testing
@testable import DesignSystem

private func requireKeyTraits<T: CaseIterable & Equatable & Hashable & Sendable>(_: T.Type) {}

private enum FrozenUnknown {
    static let japanese = "この設定値の詳細は未確認です。エージェントの設定を確認してください。"
    static let english = "Details of this setting value are unconfirmed. Check the agent settings."
}

private enum FrozenUnset {
    static let titleJA = "既定（未設定）"
    static let titleEN = "Default (unset)"
    static let explanationJA = "値は未設定です。適用される既定値はエージェントの設定を確認してください。"
    static let explanationEN = "The value is unset. Check the agent settings for the applied default."
}

private func permission(
    _ agent: UIWording.PermissionAgent,
    _ kind: UIWording.PermissionKind,
    _ value: String?,
    _ languageCode: String
) -> UIWording.PermissionWording {
    UIWording.permission(agent: agent, kind: kind, value: value, languageCode: languageCode)
}

@Suite("task-50: UIWording 権限文言の正本")
struct AcceptancePermissionWordingTests {

    @Test("PermissionAgent / PermissionKind の命名規則と集合が契約と一致する")
    func permissionTypesMatchContract() {
        requireKeyTraits(UIWording.PermissionAgent.self)
        requireKeyTraits(UIWording.PermissionKind.self)
        #expect(UIWording.PermissionAgent.allCases == [.claude, .codex, .cursor, .custom])
        #expect(UIWording.PermissionAgent.claude.rawValue == "claude")
        #expect(UIWording.PermissionAgent.codex.rawValue == "codex")
        #expect(UIWording.PermissionAgent.cursor.rawValue == "cursor")
        #expect(UIWording.PermissionAgent.custom.rawValue == "custom")
        #expect(UIWording.PermissionKind.allCases == [
            .claudePermissionMode,
            .codexApprovalPolicy,
            .codexSandboxMode,
            .codexProfile,
            .cursorApprovalMode,
            .cursorSandboxMode,
            .cursorOperationMode,
            .claudeRuleBucket,
            .cursorRuleBucket,
            .settingKeyTitle,
            .permissionsPaneIntro,
        ])
        #expect(UIWording.PermissionKind.claudePermissionMode.rawValue == "claudePermissionMode")
        #expect(UIWording.PermissionKind.codexApprovalPolicy.rawValue == "codexApprovalPolicy")
        #expect(UIWording.PermissionKind.codexSandboxMode.rawValue == "codexSandboxMode")
        #expect(UIWording.PermissionKind.codexProfile.rawValue == "codexProfile")
        #expect(UIWording.PermissionKind.cursorApprovalMode.rawValue == "cursorApprovalMode")
        #expect(UIWording.PermissionKind.cursorSandboxMode.rawValue == "cursorSandboxMode")
        #expect(UIWording.PermissionKind.cursorOperationMode.rawValue == "cursorOperationMode")
        #expect(UIWording.PermissionKind.claudeRuleBucket.rawValue == "claudeRuleBucket")
        #expect(UIWording.PermissionKind.cursorRuleBucket.rawValue == "cursorRuleBucket")
        #expect(UIWording.PermissionKind.settingKeyTitle.rawValue == "settingKeyTitle")
        #expect(UIWording.PermissionKind.permissionsPaneIntro.rawValue == "permissionsPaneIntro")
        #expect(UIWording.PermissionKind.allCases.count == 11)
        #expect(Set(UIWording.PermissionKind.allCases).count == 11)
    }

    @Test("公開関数の型が agent・kind・value・languageCode を区別する")
    func publicFunctionSignature() {
        let permissionFn: (UIWording.PermissionAgent, UIWording.PermissionKind, String?, String) -> UIWording.PermissionWording = UIWording.permission
        let launchFn: (UIWording.PermissionAgent, String, String) -> UIWording.LaunchPermissionWording = UIWording.launchPermission
        let footerFn: (String) -> String = UIWording.settingsPermissionFooter
        let ja = permissionFn(.claude, .claudePermissionMode, "manual", "ja")
        #expect(ja.title == "手動承認")
        #expect(ja.explanation == "読み取り以外は権限ルールに従って承認を求めます。実行範囲の制限とは別の設定です。")
        let launch = launchFn(.claude, "ignored", "ja")
        #expect(launch.rowLabel == "Claude Code: 承認確認を省略")
        #expect(footerFn("ja") == "変更は次回セッション開始から反映されます。承認方式と実行制限はエージェントごとに異なります。解除は信頼できるプロジェクトでのみ有効にしてください。")
    }

    @Test("Claude 権限モードの日本語表示名・説明が契約表の独立リテラルと逐語一致する")
    func claudePermissionModeJapanese() {
        let manual = permission(.claude, .claudePermissionMode, "manual", "ja")
        #expect(manual.title == "手動承認")
        #expect(manual.explanation == "読み取り以外は権限ルールに従って承認を求めます。実行範囲の制限とは別の設定です。")
        let defaultMode = permission(.claude, .claudePermissionMode, "default", "ja")
        #expect(defaultMode.title == "手動承認")
        #expect(defaultMode.explanation == "読み取り以外は権限ルールに従って承認を求めます。実行範囲の制限とは別の設定です。")
        #expect(defaultMode == manual)
        let acceptEdits = permission(.claude, .claudePermissionMode, "acceptEdits", "ja")
        #expect(acceptEdits.title == "編集を自動承認")
        #expect(acceptEdits.explanation == "ファイル編集などを自動承認します。すべてのコマンド実行を承認する設定ではありません。")
        let auto = permission(.claude, .claudePermissionMode, "auto", "ja")
        #expect(auto.title == "自動判定")
        #expect(auto.explanation == "Claude Code が操作を判定します。すべての操作を無条件に許可する設定ではありません。")
        let bypass = permission(.claude, .claudePermissionMode, "bypassPermissions", "ja")
        #expect(bypass.title == "承認確認を省略")
        #expect(bypass.explanation == "通常の承認確認を省略します。サンドボックスの解除を意味する設定ではありません。")
        let dontAsk = permission(.claude, .claudePermissionMode, "dontAsk", "ja")
        #expect(dontAsk.title == "承認が必要な操作を拒否")
        #expect(dontAsk.explanation == "事前に許可された操作などを実行し、承認が必要な操作は確認せず拒否します。")
        let plan = permission(.claude, .claudePermissionMode, "plan", "ja")
        #expect(plan.title == "計画")
        #expect(plan.explanation == "調査と計画を行うモードです。編集を進めるモードとは区別されます。")
        #expect(dontAsk.explanation != bypass.explanation)
        #expect(dontAsk.title != bypass.title)
        #expect(bypass.explanation.contains("サンドボックス") )
        #expect(!bypass.explanation.contains("すべて許可"))
        #expect(!dontAsk.explanation.contains("すべて許可"))
    }

    @Test("Claude 権限モードの英語表示名・説明が凍結リテラルと逐語一致する")
    func claudePermissionModeEnglish() {
        let manual = permission(.claude, .claudePermissionMode, "manual", "en")
        #expect(manual.title == "Manual")
        #expect(manual.explanation == "Asks for approval according to permission rules except for reads. This is separate from execution-scope limits.")
        #expect(permission(.claude, .claudePermissionMode, "default", "en") == manual)
        let acceptEdits = permission(.claude, .claudePermissionMode, "acceptEdits", "en")
        #expect(acceptEdits.title == "Accept Edits")
        #expect(acceptEdits.explanation == "Automatically approves file edits and similar actions. This does not approve every command.")
        let auto = permission(.claude, .claudePermissionMode, "auto", "en")
        #expect(auto.title == "Auto")
        #expect(auto.explanation == "Claude Code decides how to handle each action. This does not unconditionally allow every action.")
        let bypass = permission(.claude, .claudePermissionMode, "bypassPermissions", "en")
        #expect(bypass.title == "Bypass")
        #expect(bypass.explanation == "Skips the usual approval prompts. This does not disable the sandbox.")
        let dontAsk = permission(.claude, .claudePermissionMode, "dontAsk", "en")
        #expect(dontAsk.title == "Don't Ask")
        #expect(dontAsk.explanation == "Runs previously allowed actions and rejects actions that would need approval, without asking.")
        let plan = permission(.claude, .claudePermissionMode, "plan", "en")
        #expect(plan.title == "Plan")
        #expect(plan.explanation == "A mode for research and planning. It is distinct from modes that proceed with edits.")
        #expect(dontAsk.explanation != bypass.explanation)
        #expect(!bypass.explanation.lowercased().contains("disable the sandbox") || bypass.explanation.contains("does not disable the sandbox"))
        #expect(!dontAsk.title.contains("Full Access"))
        #expect(!bypass.explanation.contains("full access"))
    }

    @Test("Codex 承認方針の日英が契約表の独立リテラルと逐語一致する")
    func codexApprovalPolicyBothLanguages() {
        let untrustedJA = permission(.codex, .codexApprovalPolicy, "untrusted", "ja")
        #expect(untrustedJA.title == "信頼対象外の操作を確認")
        #expect(untrustedJA.explanation == "自動実行できる操作以外は承認を求めます。実行範囲はサンドボックス設定に従います。")
        let untrustedEN = permission(.codex, .codexApprovalPolicy, "untrusted", "en")
        #expect(untrustedEN.title == "Confirm untrusted actions")
        #expect(untrustedEN.explanation == "Asks for approval except for actions that can run automatically. Execution scope follows the sandbox setting.")
        let onRequestJA = permission(.codex, .codexApprovalPolicy, "on-request", "ja")
        #expect(onRequestJA.title == "必要時に承認を要求")
        #expect(onRequestJA.explanation == "Codex が必要と判断したときに承認を求めます。実行範囲はサンドボックス設定に従います。")
        let onRequestEN = permission(.codex, .codexApprovalPolicy, "on-request", "en")
        #expect(onRequestEN.title == "Ask when needed")
        #expect(onRequestEN.explanation == "Asks for approval when Codex decides it is needed. Execution scope follows the sandbox setting.")
        let neverJA = permission(.codex, .codexApprovalPolicy, "never", "ja")
        #expect(neverJA.title == "承認を要求しない")
        #expect(neverJA.explanation == "承認を求めず、設定された実行制限の範囲で動作します。実行制限を解除する設定ではありません。")
        let neverEN = permission(.codex, .codexApprovalPolicy, "never", "en")
        #expect(neverEN.title == "Do not ask for approval")
        #expect(neverEN.explanation == "Runs without asking for approval, within the configured execution limits. This does not lift those limits.")
        let granularJA = permission(.codex, .codexApprovalPolicy, "granular", "ja")
        #expect(granularJA.title == "項目別の承認設定")
        #expect(granularJA.explanation == "承認要求の種類ごとに扱いを定める設定です。この名前だけでは具体的な許可範囲は分かりません。")
        let granularEN = permission(.codex, .codexApprovalPolicy, "granular", "en")
        #expect(granularEN.title == "Per-item approval")
        #expect(granularEN.explanation == "Defines how each kind of approval request is handled. This name alone does not describe the allowed scope.")
        #expect(!neverJA.title.contains("すべて許可"))
        #expect(!neverJA.explanation.contains("すべて許可"))
        #expect(!neverEN.title.lowercased().contains("allow everything"))
        #expect(!neverEN.explanation.lowercased().contains("allow everything"))
    }

    @Test("Codex 実行制限の日英が契約表の独立リテラルと逐語一致する")
    func codexSandboxModeBothLanguages() {
        let readOnlyJA = permission(.codex, .codexSandboxMode, "read-only", "ja")
        #expect(readOnlyJA.title == "読み取り専用")
        #expect(readOnlyJA.explanation == "サンドボックス内での書き込みを制限します。承認を求める条件は別の設定です。")
        let readOnlyEN = permission(.codex, .codexSandboxMode, "read-only", "en")
        #expect(readOnlyEN.title == "Read-only")
        #expect(readOnlyEN.explanation == "Restricts writes inside the sandbox. Approval conditions are a separate setting.")
        let workspaceJA = permission(.codex, .codexSandboxMode, "workspace-write", "ja")
        #expect(workspaceJA.title == "作業領域への書き込み")
        #expect(workspaceJA.explanation == "作業領域など、設定された範囲への書き込みを許可します。ネットワークや保護対象の制限は別途適用されます。")
        let workspaceEN = permission(.codex, .codexSandboxMode, "workspace-write", "en")
        #expect(workspaceEN.title == "Workspace write")
        #expect(workspaceEN.explanation == "Allows writes to the workspace and other configured scopes. Network and protected-path limits still apply.")
        let fullJA = permission(.codex, .codexSandboxMode, "danger-full-access", "ja")
        #expect(fullJA.title == "サンドボックス制限なし")
        #expect(fullJA.explanation == "Codex のサンドボックスによる実行制限を外します。承認を求める条件は別の設定です。")
        let fullEN = permission(.codex, .codexSandboxMode, "danger-full-access", "en")
        #expect(fullEN.title == "No sandbox limits")
        #expect(fullEN.explanation == "Removes Codex sandbox execution limits. Approval conditions are a separate setting.")
    }

    @Test("Codex プロフィール ID と設定値を混同しない")
    func codexProfileDistinctFromSettings() {
        let readOnlyProfileJA = permission(.codex, .codexProfile, ":read-only", "ja")
        #expect(readOnlyProfileJA.title == "読み取り専用")
        #expect(readOnlyProfileJA.explanation == "読み取り専用のプロフィールです。承認方針の詳細はエージェントの設定を確認してください。")
        let readOnlyProfileEN = permission(.codex, .codexProfile, ":read-only", "en")
        #expect(readOnlyProfileEN.title == "Read Only")
        #expect(readOnlyProfileEN.explanation == "A read-only profile. Check the agent settings for approval-policy details.")
        let workspaceProfileJA = permission(.codex, .codexProfile, ":workspace", "ja")
        #expect(workspaceProfileJA.title == "作業領域への書き込み")
        #expect(workspaceProfileJA.explanation == "作業領域への書き込みを許可するプロフィールです。承認方針の詳細はエージェントの設定を確認してください。")
        let workspaceProfileEN = permission(.codex, .codexProfile, ":workspace", "en")
        #expect(workspaceProfileEN.title == "Auto")
        #expect(workspaceProfileEN.explanation == "A profile that allows workspace writes. Check the agent settings for approval-policy details.")
        let dangerProfileJA = permission(.codex, .codexProfile, ":danger-full-access", "ja")
        #expect(dangerProfileJA.title == "承認なし・実行制限なし")
        #expect(dangerProfileJA.explanation == "承認と実行制限を解除するプロフィールです。適用内容はエージェントの設定を確認してください。")
        let dangerProfileEN = permission(.codex, .codexProfile, ":danger-full-access", "en")
        #expect(dangerProfileEN.title == "Full Access")
        #expect(dangerProfileEN.explanation == "A profile that lifts approval and execution limits. Check the agent settings for what actually applies.")
        let unsetProfileJA = permission(.codex, .codexProfile, nil, "ja")
        #expect(unsetProfileJA.title == "承認設定")
        #expect(unsetProfileJA.explanation == "プロフィールは未選択です。実際の適用内容はエージェントの設定を確認してください。")
        let unsetProfileEN = permission(.codex, .codexProfile, nil, "en")
        #expect(unsetProfileEN.title == "Approval")
        #expect(unsetProfileEN.explanation == "No profile is selected. Check the agent settings for what actually applies.")
        let sandboxRead = permission(.codex, .codexSandboxMode, "read-only", "en")
        #expect(sandboxRead.title != readOnlyProfileEN.title)
        #expect(sandboxRead.explanation != readOnlyProfileEN.explanation)
        let never = permission(.codex, .codexApprovalPolicy, "never", "en")
        let dangerSandbox = permission(.codex, .codexSandboxMode, "danger-full-access", "en")
        #expect(never.title != dangerProfileEN.title)
        #expect(never.explanation != dangerSandbox.explanation)
        #expect(dangerSandbox.title != dangerProfileEN.title)
        let neverAsProfile = permission(.codex, .codexProfile, "never", "ja")
        #expect(neverAsProfile.title == "never")
        #expect(neverAsProfile.explanation == FrozenUnknown.japanese)
        let dangerAsApproval = permission(.codex, .codexApprovalPolicy, "danger-full-access", "ja")
        #expect(dangerAsApproval.title == "danger-full-access")
        #expect(dangerAsApproval.explanation == FrozenUnknown.japanese)
    }

    @Test("Cursor 承認方式・実行制限・動作モードの日英が契約表の独立リテラルと逐語一致する")
    func cursorSettingsBothLanguages() {
        let allowlistJA = permission(.cursor, .cursorApprovalMode, "allowlist", "ja")
        #expect(allowlistJA.title == "許可リストで確認")
        #expect(allowlistJA.explanation == "許可リスト外の操作では確認を求める設定です。サンドボックス設定とは別です。")
        let allowlistEN = permission(.cursor, .cursorApprovalMode, "allowlist", "en")
        #expect(allowlistEN.title == "Confirm with allowlist")
        #expect(allowlistEN.explanation == "Asks for confirmation outside the allowlist. This is separate from the sandbox setting.")
        let unrestrictedJA = permission(.cursor, .cursorApprovalMode, "unrestricted", "ja")
        #expect(unrestrictedJA.title == "承認確認を省略")
        #expect(unrestrictedJA.explanation == "操作の承認確認を省略する設定です。サンドボックス設定とは別です。")
        let unrestrictedEN = permission(.cursor, .cursorApprovalMode, "unrestricted", "en")
        #expect(unrestrictedEN.title == "Skip approval prompts")
        #expect(unrestrictedEN.explanation == "Skips approval prompts. This is separate from the sandbox setting.")
        let autoReviewJA = permission(.cursor, .cursorApprovalMode, "auto-review", "ja")
        #expect(autoReviewJA.title == "Cursor の自動判定")
        #expect(autoReviewJA.explanation == "Cursor の判定に従って操作を実行します。Claude の権限モードや Codex の承認方針とは別の設定です。")
        let autoReviewEN = permission(.cursor, .cursorApprovalMode, "auto-review", "en")
        #expect(autoReviewEN.title == "Cursor auto review")
        #expect(autoReviewEN.explanation == "Runs actions according to Cursor's judgment. This is a different setting from Claude permission modes and Codex approval policy.")
        let enabledJA = permission(.cursor, .cursorSandboxMode, "enabled", "ja")
        #expect(enabledJA.title == "実行制限を有効化")
        #expect(enabledJA.explanation == "コマンドをサンドボックス内で実行する設定です。")
        let enabledEN = permission(.cursor, .cursorSandboxMode, "enabled", "en")
        #expect(enabledEN.title == "Enable execution limits")
        #expect(enabledEN.explanation == "Runs commands inside a sandbox.")
        let disabledJA = permission(.cursor, .cursorSandboxMode, "disabled", "ja")
        #expect(disabledJA.title == "実行制限を無効化")
        #expect(disabledJA.explanation == "サンドボックスによる実行制限を無効にする設定です。")
        let disabledEN = permission(.cursor, .cursorSandboxMode, "disabled", "en")
        #expect(disabledEN.title == "Disable execution limits")
        #expect(disabledEN.explanation == "Disables sandbox execution limits.")
        let agentJA = permission(.cursor, .cursorOperationMode, nil, "ja")
        #expect(agentJA.title == "エージェント")
        #expect(agentJA.explanation == "通常の作業モードです。承認方式や実行制限を選ぶ項目ではありません。")
        let agentEN = permission(.cursor, .cursorOperationMode, nil, "en")
        #expect(agentEN.title == "Agent")
        #expect(agentEN.explanation == "The usual working mode. This is not a control for approval method or execution limits.")
        let askJA = permission(.cursor, .cursorOperationMode, "ask", "ja")
        #expect(askJA.title == "質問")
        #expect(askJA.explanation == "質問向けの動作モードです。承認方式を選ぶ項目ではありません。")
        let askEN = permission(.cursor, .cursorOperationMode, "ask", "en")
        #expect(askEN.title == "Ask")
        #expect(askEN.explanation == "A question-oriented working mode. This is not a control for choosing an approval method.")
        let planJA = permission(.cursor, .cursorOperationMode, "plan", "ja")
        #expect(planJA.title == "計画")
        #expect(planJA.explanation == "計画向けの動作モードです。承認方式や実行制限を選ぶ項目ではありません。")
        let planEN = permission(.cursor, .cursorOperationMode, "plan", "en")
        #expect(planEN.title == "Plan")
        #expect(planEN.explanation == "A planning-oriented working mode. This is not a control for approval method or execution limits.")
        #expect(unrestrictedEN.title != "Bypass")
        #expect(askEN.title == "Ask")
    }

    @Test("同じ raw value を別のエージェント・設定種類で問い合わせても混同しない")
    func sameRawValueDoesNotCrossKinds() {
        let cursorAsk = permission(.cursor, .cursorOperationMode, "ask", "ja")
        let claudeAskRule = permission(.claude, .claudeRuleBucket, "ask", "ja")
        let claudeAskMode = permission(.claude, .claudePermissionMode, "ask", "ja")
        let cursorAskApproval = permission(.cursor, .cursorApprovalMode, "ask", "ja")
        #expect(cursorAsk.title == "質問")
        #expect(claudeAskRule.title == "確認する")
        #expect(claudeAskMode.title == "ask")
        #expect(claudeAskMode.explanation == FrozenUnknown.japanese)
        #expect(cursorAskApproval.title == "ask")
        #expect(cursorAskApproval.explanation == FrozenUnknown.japanese)
        #expect(cursorAsk.title != claudeAskRule.title)
        #expect(cursorAsk.explanation != claudeAskRule.explanation)
        let claudePlan = permission(.claude, .claudePermissionMode, "plan", "ja")
        let cursorPlan = permission(.cursor, .cursorOperationMode, "plan", "ja")
        #expect(claudePlan.title == "計画")
        #expect(cursorPlan.title == "計画")
        #expect(claudePlan.explanation == "調査と計画を行うモードです。編集を進めるモードとは区別されます。")
        #expect(cursorPlan.explanation == "計画向けの動作モードです。承認方式や実行制限を選ぶ項目ではありません。")
        #expect(claudePlan.explanation != cursorPlan.explanation)
        let autoClaude = permission(.claude, .claudePermissionMode, "auto", "ja")
        let autoCursor = permission(.cursor, .cursorOperationMode, "auto", "ja")
        #expect(autoClaude.title == "自動判定")
        #expect(autoCursor.title == "auto")
        #expect(autoCursor.explanation == FrozenUnknown.japanese)
        let allowClaude = permission(.claude, .claudeRuleBucket, "allow", "ja")
        let allowCursor = permission(.cursor, .cursorRuleBucket, "allow", "ja")
        #expect(allowClaude.title == "許可")
        #expect(allowCursor.title == "許可")
        #expect(allowClaude.explanation == "確認なしで実行を許可するルールです。拒否ルールなど、他の権限設定も適用されます。")
        #expect(allowCursor.explanation == "確認なしで実行を許可するルールです。拒否ルールが優先されます。")
        #expect(allowClaude.explanation != allowCursor.explanation)
    }

    @Test("ルール区分の日英が契約表の独立リテラルと逐語一致する")
    func ruleBucketsBothLanguages() {
        let claudeAllowJA = permission(.claude, .claudeRuleBucket, "allow", "ja")
        #expect(claudeAllowJA.title == "許可")
        #expect(claudeAllowJA.explanation == "確認なしで実行を許可するルールです。拒否ルールなど、他の権限設定も適用されます。")
        let claudeAllowEN = permission(.claude, .claudeRuleBucket, "allow", "en")
        #expect(claudeAllowEN.title == "Allow")
        #expect(claudeAllowEN.explanation == "Permits execution without confirmation. Other permission settings, such as deny rules, also apply.")
        let claudeAskJA = permission(.claude, .claudeRuleBucket, "ask", "ja")
        #expect(claudeAskJA.title == "確認する")
        #expect(claudeAskJA.explanation == "実行前に確認を求めるルールです。確認できないモードでは実行が拒否される場合があります。")
        let claudeAskEN = permission(.claude, .claudeRuleBucket, "ask", "en")
        #expect(claudeAskEN.title == "Ask to confirm")
        #expect(claudeAskEN.explanation == "Asks for confirmation before execution. In modes that cannot confirm, execution may be denied.")
        let claudeDenyJA = permission(.claude, .claudeRuleBucket, "deny", "ja")
        #expect(claudeDenyJA.title == "拒否")
        #expect(claudeDenyJA.explanation == "実行を拒否するルールです。許可ルールより優先されます。")
        let claudeDenyEN = permission(.claude, .claudeRuleBucket, "deny", "en")
        #expect(claudeDenyEN.title == "Deny")
        #expect(claudeDenyEN.explanation == "Denies execution. Takes precedence over allow rules.")
        let cursorAllowJA = permission(.cursor, .cursorRuleBucket, "allow", "ja")
        #expect(cursorAllowJA.title == "許可")
        #expect(cursorAllowJA.explanation == "確認なしで実行を許可するルールです。拒否ルールが優先されます。")
        let cursorAllowEN = permission(.cursor, .cursorRuleBucket, "allow", "en")
        #expect(cursorAllowEN.title == "Allow")
        #expect(cursorAllowEN.explanation == "Permits execution without confirmation. Deny rules take precedence.")
        let cursorDenyJA = permission(.cursor, .cursorRuleBucket, "deny", "ja")
        #expect(cursorDenyJA.title == "拒否")
        #expect(cursorDenyJA.explanation == "実行を拒否するルールです。許可ルールより優先されます。")
        let cursorDenyEN = permission(.cursor, .cursorRuleBucket, "deny", "en")
        #expect(cursorDenyEN.title == "Deny")
        #expect(cursorDenyEN.explanation == "Denies execution. Takes precedence over allow rules.")
        #expect(claudeAskEN.title != "Ask")
        #expect(permission(.cursor, .cursorRuleBucket, "ask", "ja").title == "ask")
        #expect(permission(.cursor, .cursorRuleBucket, "ask", "ja").explanation == FrozenUnknown.japanese)
    }

    @Test("設定項目名と管理画面の導入文が凍結リテラルと逐語一致する")
    func settingKeyTitlesAndPaneIntros() {
        #expect(permission(.codex, .settingKeyTitle, "approval_policy", "ja").title == "承認方針")
        #expect(permission(.codex, .settingKeyTitle, "approval_policy", "en").title == "Approval policy")
        #expect(permission(.codex, .settingKeyTitle, "sandbox_mode", "ja").title == "実行制限（サンドボックス）")
        #expect(permission(.codex, .settingKeyTitle, "sandbox_mode", "en").title == "Execution limits (sandbox)")
        #expect(permission(.cursor, .settingKeyTitle, "approvalMode", "ja").title == "承認方式")
        #expect(permission(.cursor, .settingKeyTitle, "approvalMode", "en").title == "Approval method")
        #expect(permission(.cursor, .settingKeyTitle, "sandbox.mode", "ja").title == "実行制限（サンドボックス）")
        #expect(permission(.cursor, .settingKeyTitle, "sandbox.mode", "en").title == "Execution limits (sandbox)")
        #expect(permission(.codex, .settingKeyTitle, "approval_policy", "ja").title != permission(.cursor, .settingKeyTitle, "approvalMode", "ja").title)
        let claudeIntroJA = permission(.claude, .permissionsPaneIntro, nil, "ja")
        #expect(claudeIntroJA.title == "権限")
        #expect(claudeIntroJA.explanation == "対話 TUI の /permissions に相当します。~/.claude/settings.json の permissions を編集します。ルール編集は設定画面の起動時トグルとは別の設定です。")
        let claudeIntroEN = permission(.claude, .permissionsPaneIntro, nil, "en")
        #expect(claudeIntroEN.title == "Permissions")
        #expect(claudeIntroEN.explanation == "Equivalent to /permissions in the interactive TUI. Edits permissions in ~/.claude/settings.json. Rule editing is a different setting from the launch toggle in Settings.")
        let cursorIntroJA = permission(.cursor, .permissionsPaneIntro, nil, "ja")
        #expect(cursorIntroJA.title == "権限")
        #expect(cursorIntroJA.explanation == "~/.cursor/cli-config.json の permissions を編集します。拒否は許可より優先されます。ルール編集は設定画面の起動時トグルとは別の設定です。")
        let cursorIntroEN = permission(.cursor, .permissionsPaneIntro, nil, "en")
        #expect(cursorIntroEN.title == "Permissions")
        #expect(cursorIntroEN.explanation == "Edits permissions in ~/.cursor/cli-config.json. Deny rules take precedence over allow. Rule editing is a different setting from the launch toggle in Settings.")
        #expect(claudeIntroJA.explanation.contains("~/.claude/settings.json"))
        #expect(cursorIntroJA.explanation.contains("~/.cursor/cli-config.json"))
    }

    @Test("組み込み3エージェントとカスタムの起動説明が契約表の独立リテラルと逐語一致する")
    func launchPermissionRows() {
        let claudeJA = UIWording.launchPermission(agent: .claude, displayName: "ignored", languageCode: "ja")
        #expect(claudeJA.rowLabel == "Claude Code: 承認確認を省略")
        #expect(claudeJA.offExplanation == "次回開始時に自動判定（auto）を指定します。")
        #expect(claudeJA.onExplanation == "次回開始時に承認確認の省略（bypassPermissions）を指定します。サンドボックスの解除を意味しません。")
        let claudeEN = UIWording.launchPermission(agent: .claude, displayName: "ignored", languageCode: "en")
        #expect(claudeEN.rowLabel == "Claude Code: Skip approval prompts")
        #expect(claudeEN.offExplanation == "Specifies auto (automatic judgment) at the next launch.")
        #expect(claudeEN.onExplanation == "Specifies bypassPermissions (skip approval prompts) at the next launch. This does not disable the sandbox.")
        let codexJA = UIWording.launchPermission(agent: .codex, displayName: "ignored", languageCode: "ja")
        #expect(codexJA.rowLabel == "Codex: 承認と実行制限を解除")
        #expect(codexJA.offExplanation == "チャットでは on-request と workspace-write を指定します。ターミナルでは解除引数を付けず、Codex の設定に従います。")
        #expect(codexJA.onExplanation == "チャットでは never と danger-full-access を指定します。ターミナルでは承認とサンドボックスの解除引数を付けます。")
        let codexEN = UIWording.launchPermission(agent: .codex, displayName: "ignored", languageCode: "en")
        #expect(codexEN.rowLabel == "Codex: Lift approval and execution limits")
        #expect(codexEN.offExplanation == "Specifies on-request and workspace-write in chat. Terminal launches omit the lift arguments and follow Codex settings.")
        #expect(codexEN.onExplanation == "Specifies never and danger-full-access in chat. Terminal launches add arguments that lift approval and the sandbox.")
        let cursorJA = UIWording.launchPermission(agent: .cursor, displayName: "ignored", languageCode: "ja")
        #expect(cursorJA.rowLabel == "Cursor: 承認と実行制限を解除")
        #expect(cursorJA.offExplanation == "次回開始時に --auto-review と --sandbox enabled を指定します。")
        #expect(cursorJA.onExplanation == "次回開始時に --force と --sandbox disabled を指定します。")
        let cursorEN = UIWording.launchPermission(agent: .cursor, displayName: "ignored", languageCode: "en")
        #expect(cursorEN.rowLabel == "Cursor: Lift approval and execution limits")
        #expect(cursorEN.offExplanation == "Specifies --auto-review and --sandbox enabled at the next launch.")
        #expect(cursorEN.onExplanation == "Specifies --force and --sandbox disabled at the next launch.")
        let customJA = UIWording.launchPermission(agent: .custom, displayName: "My Agent", languageCode: "ja")
        #expect(customJA.rowLabel == "My Agent: 起動時の権限設定")
        #expect(customJA.offExplanation == "このエージェントの起動設定に従います。許可範囲はエージェント設定を確認してください。")
        #expect(customJA.onExplanation == "このエージェントの起動設定に従います。許可範囲はエージェント設定を確認してください。")
        let customEN = UIWording.launchPermission(agent: .custom, displayName: "My Agent", languageCode: "en")
        #expect(customEN.rowLabel == "My Agent: Launch permission settings")
        #expect(customEN.offExplanation == "Follows this agent's launch settings. Check the agent settings for the allowed scope.")
        #expect(customEN.onExplanation == "Follows this agent's launch settings. Check the agent settings for the allowed scope.")
        let otherCustom = UIWording.launchPermission(agent: .custom, displayName: "Other", languageCode: "ja")
        #expect(otherCustom.rowLabel == "Other: 起動時の権限設定")
        #expect(customJA.rowLabel != claudeJA.rowLabel)
        #expect(!customJA.rowLabel.contains("フルアクセス"))
        #expect(!customEN.rowLabel.contains("Full Access"))
        #expect(claudeJA.offExplanation != claudeJA.onExplanation)
        #expect(codexJA.offExplanation != cursorJA.offExplanation)
        #expect(UIWording.settingsPermissionFooter(languageCode: "ja") == "変更は次回セッション開始から反映されます。承認方式と実行制限はエージェントごとに異なります。解除は信頼できるプロジェクトでのみ有効にしてください。")
        #expect(UIWording.settingsPermissionFooter(languageCode: "en") == "Changes take effect from the next session start. Approval method and execution limits differ by agent. Enable lift only on projects you trust.")
    }

    @Test("未知値は原文を表示し、未設定と各 nil の意味を混同しない")
    func unknownUnsetAndNilMeanings() {
        let unknownClaude = permission(.claude, .claudePermissionMode, "mystery", "ja")
        #expect(unknownClaude.title == "mystery")
        #expect(unknownClaude.explanation == FrozenUnknown.japanese)
        let unknownClaudeEN = permission(.claude, .claudePermissionMode, "mystery", "en")
        #expect(unknownClaudeEN.title == "mystery")
        #expect(unknownClaudeEN.explanation == FrozenUnknown.english)
        let unknownProfile = permission(.codex, .codexProfile, ":experimental", "ja")
        #expect(unknownProfile.title == ":experimental")
        #expect(unknownProfile.explanation == FrozenUnknown.japanese)
        let unknownProfileEN = permission(.codex, .codexProfile, ":experimental", "en")
        #expect(unknownProfileEN.title == ":experimental")
        #expect(unknownProfileEN.explanation == FrozenUnknown.english)
        let unsetApprovalJA = permission(.codex, .codexApprovalPolicy, nil, "ja")
        #expect(unsetApprovalJA.title == FrozenUnset.titleJA)
        #expect(unsetApprovalJA.explanation == FrozenUnset.explanationJA)
        let unsetApprovalEN = permission(.codex, .codexApprovalPolicy, nil, "en")
        #expect(unsetApprovalEN.title == FrozenUnset.titleEN)
        #expect(unsetApprovalEN.explanation == FrozenUnset.explanationEN)
        let unsetSandbox = permission(.codex, .codexSandboxMode, nil, "ja")
        #expect(unsetSandbox.title == FrozenUnset.titleJA)
        #expect(unsetSandbox.explanation == FrozenUnset.explanationJA)
        let unsetCursorApproval = permission(.cursor, .cursorApprovalMode, nil, "ja")
        #expect(unsetCursorApproval.title == FrozenUnset.titleJA)
        #expect(unsetCursorApproval.explanation == FrozenUnset.explanationJA)
        let unsetCursorSandbox = permission(.cursor, .cursorSandboxMode, nil, "en")
        #expect(unsetCursorSandbox.title == FrozenUnset.titleEN)
        #expect(unsetCursorSandbox.explanation == FrozenUnset.explanationEN)
        let cursorNilMode = permission(.cursor, .cursorOperationMode, nil, "ja")
        #expect(cursorNilMode.title == "エージェント")
        #expect(cursorNilMode.title != FrozenUnset.titleJA)
        let profileNil = permission(.codex, .codexProfile, nil, "ja")
        #expect(profileNil.title == "承認設定")
        #expect(profileNil.title != FrozenUnset.titleJA)
        let claudeNil = permission(.claude, .claudePermissionMode, nil, "ja")
        let bypass = permission(.claude, .claudePermissionMode, "bypassPermissions", "ja")
        #expect(claudeNil.title != bypass.title)
        #expect(claudeNil.explanation == FrozenUnknown.japanese)
        #expect(claudeNil.title != FrozenUnset.titleJA)
        #expect(claudeNil.title != "bypassPermissions")
        #expect(unknownClaude.title != FrozenUnset.titleJA)
        #expect(permission(.codex, .codexApprovalPolicy, "never", "ja").title != FrozenUnset.titleJA)
        let unknownCodexSandboxJA = permission(.codex, .codexSandboxMode, "mystery-sandbox", "ja")
        #expect(unknownCodexSandboxJA.title == "mystery-sandbox")
        #expect(unknownCodexSandboxJA.explanation == FrozenUnknown.japanese)
        let unknownCursorSandboxEN = permission(.cursor, .cursorSandboxMode, "mystery-sandbox", "en")
        #expect(unknownCursorSandboxEN.title == "mystery-sandbox")
        #expect(unknownCursorSandboxEN.explanation == FrozenUnknown.english)
        let unsetCodexSandboxEN = permission(.codex, .codexSandboxMode, nil, "en")
        #expect(unsetCodexSandboxEN.title == FrozenUnset.titleEN)
        #expect(unsetCodexSandboxEN.explanation == FrozenUnset.explanationEN)
        let unsetCursorApprovalEN = permission(.cursor, .cursorApprovalMode, nil, "en")
        #expect(unsetCursorApprovalEN.title == FrozenUnset.titleEN)
        #expect(unsetCursorApprovalEN.explanation == FrozenUnset.explanationEN)
        let unsetCursorSandboxJA = permission(.cursor, .cursorSandboxMode, nil, "ja")
        #expect(unsetCursorSandboxJA.title == FrozenUnset.titleJA)
        #expect(unsetCursorSandboxJA.explanation == FrozenUnset.explanationJA)
        let spacedUnknown = permission(.claude, .claudePermissionMode, " mystery\nvalue ", "ja")
        #expect(spacedUnknown.title == " mystery\nvalue ")
        #expect(spacedUnknown.explanation == FrozenUnknown.japanese)
        let newlineUnknownEN = permission(.codex, .codexProfile, ":\nexperimental\t", "en")
        #expect(newlineUnknownEN.title == ":\nexperimental\t")
        #expect(newlineUnknownEN.explanation == FrozenUnknown.english)
        let agentIgnored = permission(.claude, .codexApprovalPolicy, "never", "ja")
        #expect(agentIgnored.title == "never")
        #expect(agentIgnored.explanation == FrozenUnknown.japanese)
        #expect(agentIgnored.title != permission(.codex, .codexApprovalPolicy, "never", "ja").title)
        let kindKeptAgentChanged = permission(.cursor, .claudePermissionMode, "auto", "ja")
        #expect(kindKeptAgentChanged.title == "auto")
        #expect(kindKeptAgentChanged.explanation == FrozenUnknown.japanese)
        #expect(kindKeptAgentChanged.title != permission(.claude, .claudePermissionMode, "auto", "ja").title)
        let launchRegional = UIWording.launchPermission(agent: .claude, displayName: "x", languageCode: "ja-JP")
        #expect(launchRegional.rowLabel == "Claude Code: 承認確認を省略")
        #expect(launchRegional.offExplanation == "次回開始時に自動判定（auto）を指定します。")
        let launchUnsupported = UIWording.launchPermission(agent: .codex, displayName: "x", languageCode: "zh")
        #expect(launchUnsupported.rowLabel == "Codex: 承認と実行制限を解除")
        let launchEnglishRegion = UIWording.launchPermission(agent: .cursor, displayName: "x", languageCode: "en-US")
        #expect(launchEnglishRegion.onExplanation == "Specifies --force and --sandbox disabled at the next launch.")
        #expect(UIWording.launchPermission(agent: .custom, displayName: "My Agent", languageCode: "fr").rowLabel == "My Agent: 起動時の権限設定")
        #expect(UIWording.launchPermission(agent: .custom, displayName: "My Agent", languageCode: "en_GB").rowLabel == "My Agent: Launch permission settings")
    }

    @Test("日本語・英語・未対応言語、言語変更後の再取得")
    func languageSwitchFallbackAndRestore() {
        let firstJA = permission(.claude, .claudePermissionMode, "auto", "ja")
        let thenEN = permission(.claude, .claudePermissionMode, "auto", "en")
        let backJA = permission(.claude, .claudePermissionMode, "auto", "ja")
        #expect(firstJA.title == "自動判定")
        #expect(thenEN.title == "Auto")
        #expect(backJA.title == "自動判定")
        #expect(firstJA == backJA)
        #expect(firstJA != thenEN)
        #expect(permission(.claude, .claudePermissionMode, "auto", "zh").title == "自動判定")
        #expect(permission(.claude, .claudePermissionMode, "auto", "fr").title == "自動判定")
        #expect(permission(.claude, .claudePermissionMode, "auto", "").title == "自動判定")
        #expect(permission(.claude, .claudePermissionMode, "auto", "ja-JP").title == "自動判定")
        #expect(permission(.claude, .claudePermissionMode, "auto", "ja_JP").title == "自動判定")
        #expect(permission(.claude, .claudePermissionMode, "auto", "JA").title == "自動判定")
        #expect(permission(.claude, .claudePermissionMode, "auto", "en-US").title == "Auto")
        #expect(permission(.claude, .claudePermissionMode, "auto", "en_GB").title == "Auto")
        #expect(permission(.claude, .claudePermissionMode, "auto", "EN").title == "Auto")
        #expect(permission(.cursor, .cursorOperationMode, "ask", "en-US").title == "Ask")
        #expect(permission(.cursor, .cursorOperationMode, "ask", "de").title == "質問")
        #expect(UIWording.settingsPermissionFooter(languageCode: "zh") == "変更は次回セッション開始から反映されます。承認方式と実行制限はエージェントごとに異なります。解除は信頼できるプロジェクトでのみ有効にしてください。")
        #expect(UIWording.settingsPermissionFooter(languageCode: "en-US") == "Changes take effect from the next session start. Approval method and execution limits differ by agent. Enable lift only on projects you trust.")
        let launchJA = UIWording.launchPermission(agent: .codex, displayName: "x", languageCode: "ja")
        let launchEN = UIWording.launchPermission(agent: .codex, displayName: "x", languageCode: "en")
        let launchBack = UIWording.launchPermission(agent: .codex, displayName: "x", languageCode: "ja")
        #expect(launchJA.rowLabel == launchBack.rowLabel)
        #expect(launchJA.rowLabel != launchEN.rowLabel)
        #expect(UIWording.text(.planOption, languageCode: "ja") == "計画")
        #expect(UIWording.text(.planOption, languageCode: "en") == "Plan")
        #expect(UIWording.text(.permissionLabel, languageCode: "ja") == "承認設定")
        #expect(UIWording.text(.modeLabel, languageCode: "en") == "Mode")
    }
}
